### ISSUE TITLE
Can not identify requirement -lcsv_parser 

### ISSUE THREAD

**Issue by Santara** [TianyuGuCMU/Simulator#1]
Hi,
I am deeply interested in the FastSim simulator and am looking forward to using it in my research. One of the dependencies of the Simulator is ```csv_parser``` as suggested by the line 
```LIBS = -lqwt -lproj -lgsl -lgslcblas -lm -lpthread -lrt -lGL -lGLU -lglut -lcsv_parser -lfftw3```
in ```dev.pro```.  
I am not being able to install this dependency. Could you please help me identify the package and how to install it?
Thank you
Anirban

**Comment by donnydcy** [comment]
Hello Anirban,

Thanks for your feedback. Sorry for convenience, I found that our previous csv_parser library is invalid now, you can try this one in Github, it seems the same. Let us know whether it works. Or we will upgrade the simulator.
https://github.com/erogol/csv-parser-cplusplus

Regards,
C.D

**Comment by Santara** [comment]
Thank you for pointing this out!
This solved the problem.

**Comment by mrasyid** [comment]
Hello Santara, I just wonder did you manage to run the Simulator? I have also solve this -lcsv_parser problem, and after compilation done successfully  in qtcreator, I ended up having this error message: "/home/Work/Simulator/build-dev-Desktop-Debug/dev crashed". Did you get this error message before?
